name: loopin_mvp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

  # 소셜 로그인
  google_sign_in: ^6.2.1
  kakao_flutter_sdk_user: ^1.8.0

  # QR 스캔
  mobile_scanner: ^7.0.0

  # 네이버 지도
  flutter_naver_map: ^1.3.1

  # 위치 권한 요청
  permission_handler: ^11.0.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_icon.png
    - assets/kakao_icon.png
    - assets/marker.png